### ISSUE TITLE
ReCraft+ 2.0 gives sha1 hash error on Modrinth

### ISSUE THREAD

**Issue by TheRisingUnited** [wiktormalyska/ReCraft#1]
I asked about it and a Modrinth Team Member said it was incorrectly formatted and needs to be reuploaded
![image](https://github.com/wiktormalyska/ReCraft/assets/42981157/517408a8-f416-4967-ab35-5be32da062a1)

**Comment by wiktormalyska** [comment]
Some mods got removed from modrinth. Reuploading pack
