### ISSUE TITLE
Modrinth Install Error

### ISSUE THREAD

**Issue by Gainee** [wiktormalyska/ReCraft#2]
![image](https://github.com/wiktormalyska/ReCraft/assets/51374682/5223c54c-9758-4142-b407-adef1f99d5c6)

As you can see in the image, i can't download the modpack on Modrinth App.

**Comment by wiktormalyska** [comment]
its modrinth launcher error, try downloading via atlaucner

**Comment by Gainee** [comment]
![image](https://github.com/wiktormalyska/ReCraft/assets/51374682/978a7e14-3e4d-45b2-87e0-0d2aff2d6945)
I tried on ATLauncher but error again.

**Comment by wiktormalyska** [comment]
3.2 version works
