### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ghosticlol** [wiktormalyska/ReCraft#3]
Everytime I try to download the modpack from somewhere (modrinth as an example) I get a download error.

![Screenshot 2023-09-02 113907](https://github.com/wiktormalyska/ReCraft/assets/102996767/4e3f9f78-c9e9-467a-b768-ec736cfc41f5)

**Comment by wiktormalyska** [comment]
I will try to figure out which mods were recently deleted, that's probably an issue

**Comment by ghosticlol** [comment]
Okay, thank you

**Comment by wiktormalyska** [comment]
3.2 version works
