### ISSUE TITLE
Download Broken - Possible Issue with Solas Shader

### ISSUE THREAD

**Issue by danhanly** [wiktormalyska/ReCraft#5]
Getting the sha1 error on install.

I decided to try and re-assemble the pack so I could play on my server still, and the only mod that also caused the sha1 error when installing manually was the Solas Shader.

**Comment by Niciswelt** [comment]
Still having the same Problem, do you still have the workaround? I can't find the files I need anywhere, only Modrinth (which doesn't let me download)

**Comment by RobertLupas** [comment]
Same as #4
That one has a better title, that describes the problem.

**Comment by rkohalmy** [comment]
This is the issue I get with downloading. 

`Error downloading translucent-glass-0.1.1.jar from https://cdn.modrinth.com/data/AJzlbbzZ/versions/y0COths1/translucent-glass-0.1.1.jar. Expected hash of 9a1fdf7e9f281500a874a22990fce5d4befe5a30 (with size of 100564) but got b66c946204929f571bdd1001f4cd6ae3391c81c1 (with size of 99662) instead. Copied to FailedDownloads folder & cancelling install! (60/8)`

**Comment by wiktormalyska** [comment]
Posted remake v2 of modpack
